CREATE TABLE IF NOT EXISTS _user (
  id BIGINT NOT NULL AUTO_INCREMENT,
  name VARCHAR(255) NOT NULL,
  password VARCHAR(255) NOT NULL,
  role ENUM('USER', 'ADMIN') NOT NULL DEFAULT 'USER',
  PRIMARY KEY (id)
);

INSERT INTO _user (name, password, role) VALUES
('test', '$2a$12$Of9uRD6zIJiKQFS0AQ97U.jU/69F4VWFhsPtGJTJbU/yGe2DNIsoW', 'USER');